### ISSUE TITLE
Home page [epic] 

### ISSUE THREAD

**Issue by ABatalov** [scholokov/qax-portal-2#56]
This page consist of:  

- [ ] Greetings 
- [ ] Start 
- [ ] Direction 
- [ ] Choose your derection 
- [ ] Header 
- [ ] Success cases block  
- [ ] Offers 
- [ ] Why choose us? - new block 
- [ ] Form 
- [ ] Footer

**Comment by ABatalov** [comment]
MVP

**Comment by ABatalov** [comment]
https://github.com/scholokov/qax-portal-2/issues/37 - ready for testing  

https://github.com/scholokov/qax-portal-2/issues/38  - ready for testing  

https://github.com/scholokov/qax-portal-2/issues/162 - ready for testing

**Comment by BatalovaOlha** [comment]
#123

**Comment by BatalovaOlha** [comment]
#174

**Comment by BatalovaOlha** [comment]
#251
