### ISSUE TITLE
Projects [epic] 

### ISSUE THREAD

**Issue by ABatalov** [scholokov/qax-portal-2#60]
This page consist of: 

- [ ] Lists of projects 
- [ ] Each project must consist whis information: https://docs.google.com/spreadsheets/d/1FOOjLA0eG21b-QI6GIuRGfYNA-BsfEV7iJ9U_d73ZT8/edit#gid=0 
- [ ] Manual for portal project
